---
title: Loud Saturdaze
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Your favorite music blog''s, favorite music blog. excerpt_separator:
  <-break->

'
baseurl: 
url: http://loudsaturdaze.io
twitter_username: loudsaturdaze
github_username: tbrangman
